### PR TITLE
Added CAddTensorTable.lua

### PR DESCRIPTION
**Pull request by sahiliitm**

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@sahiliitm Looks good. Nice touch on the doc. Could you add a unit test? Also, your last commit didn't get associated to your github account.

**Comment by sahiliitm** [comment]
@nicholas-leonard 
What can I do to make sure that the commit gets associated with my account?

Thanks

**Comment by nicholas-leonard** [comment]
You need to configure your github client to use ssh keys and be properly linked to your github account. https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#common-reasons-that-contributions-are-not-counted

**Comment by sahiliitm** [comment]
Done, thanks for that.

**Comment by nicholas-leonard** [comment]
@sahiliitm Thanks. Nice PR!

**Pull request merged**
