### PR TITLE
sharedClone supports nngraph's nn.gModule

### PR DESCRIPTION
**Pull request by nicholas-leonard**
Also includes a fix of nn.OneHot and  an extension of getParameters that makes it work with hidden modules.

### CODE REVIEW

**Comment by nhynes** [comment]
What should be done when one _wants_ to hide a module (i.e. to prevent training)? It feels wrong to have to copy+paste in the original `nn.Module` implementation.

**Comment by nicholas-leonard** [comment]
@nhynes What exactly do you mean by prevent training? Do you mean prevent shared parameters? 

Also, what do you mean by copy-past in original nn.Module?

**Comment by nhynes** [comment]
No, I mean that I have a model that subclasses nn.Container and the model, itself, contains sub-models that I I don't want to train. I _do_, however, want to be able to access these sub-modules later, so I store them as `self.whatever`. In keeping with the nn.Container interface, I simply don't add them to `self.modules`. The issue, then, is that the dpnn's overridden `Module:getParameters`, by scanning the model's table, finds these hidden sub-models and extracts their parameters.

Ideally, there would be some simple way to modify `parameters()` or set some flag (e.g, `self.deepSearchParams = false`) so that I get the functionality of the original, non-table-examining `Module:getParameters` without having to doubly-override `getParameters` using the pre-`require 'dpnn'` version.

**Comment by nicholas-leonard** [comment]
@nhynes You can set [`module.dpnn_getParameters_found = true`](https://github.com/Element-Research/dpnn/blob/master/Module.lua#L181) on all the modules that you don't want to include in `getParameters`. Does that work for you?

**Comment by nhynes** [comment]
Ah ha, it works! Many thanks.

**Pull request merged**
