### PR TITLE
Removing modules that have already been moved over to nn as these are…

### PR DESCRIPTION
**Pull request by richardassar**
… causing users to experiece errors when requiring
e.g. "class nn.Decorator has been already assigned a parent class"

### CODE REVIEW

**Comment by richardassar** [comment]
http://stackoverflow.com/questions/43911320/in-function-error-root-torch-install-share-lua-5-1-trepl-init-lua389-in-fun/43915000

**Comment by htoyryla** [comment]
I faced this problem today, dpnn installs but require fails on latest torch/nn. Was about to post an issue when I noticed this pull request. Will download the richardassar version and install from local copy now.

**Comment by richardassar** [comment]
I think @nicholas-leonard maybe forgot to push `dpnn` changes whilst moving things around.

**Comment by nicholas-leonard** [comment]
@richardassar Thanks!

**Pull request merged**
