### PR TITLE
One-to-many version of ZipTable

### PR DESCRIPTION
**Pull request by boknilev**
This version zips a vector with table of vectors.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
Nice!

Could you add a unit test in test/test.lua and doc to README.md. It doesn't need to be complicated. Also, you will need to include the file via init.lua.

**Comment by boknilev** [comment]
Ok, I think I'm done. Could you have a look, especially at the last test I added in the unit tests? 
(BTW, you can just take the last version of the README, since I just fixed a few typos)

**Comment by nicholas-leonard** [comment]
Test passed on my end. Doc looks great. Thanks @boknilev !

**Comment by boknilev** [comment]
No problem, @nicholas-leonard , glad it helps!

**Pull request merged**
